print("Hello World! - From Group 7")
print("1. Maghanoy, Lance Gabriel - Designer")
print("2.Panti, Joe Tykes S. -- Backend")
print("3. Boneza, Marc Oliver M. - Tester")
print("4.Baquiran,Mark Ryan J. - Fullstack")
print("5. SANTOS, JUSTINE KYLE A. Frontend")
